Version: 1.0.0

# 该项的更改需要重启服务器才能生效
RegisterCommand:
  reload:
    enable: true
    alias: "none"
  help:
    enable: true
    alias: "none"
  craft:
    enable: true
    alias: "craft"
  ec:
    enable: true
    alias: "ec"
